import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import ContextProvider from "@/context";

const font = Nunito({subsets: ["latin"]});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={font.className}
      >
        <ContextProvider >
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
